inoremap jj <Esc>
set incsearch
set number

" Pathogen for plugins
" https://github.com/tpope/vim-pathogen
execute pathogen#infect()

syntax on
filetype plugin indent on

" 4 spaces instead of tabs
set tabstop=4
set shiftwidth=4
set expandtab

" 2 spaces for Rails
autocmd Filetype html setlocal ts=2 sw=2 expandtab
autocmd Filetype ruby setlocal ts=2 sw=2 expandtab
autocmd Filetype javascript setlocal ts=4 sw=4 sts=0 noexpandtab

" Use ctrl + direction for pane navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" show the cursor position all the time
set ruler

" Display extra whitespace
set list listchars=tab:Â»Â·,trail:Â·,nbsp:Â·

" Use one space, not two, after punctuation.
set nojoinspaces

" Make it obvious where 80 characters is
set textwidth=80
set colorcolumn=+1

" Disable arrow keys for navigation
nnoremap <Left> :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up> :echoe "Use k"<CR>
nnoremap <Down> :echoe "Use j"<CR>
