inoremap jj <Esc>
set incsearch
set number

" Pathogen for plugins
" https://github.com/tpope/vim-pathogen
execute pathogen#infect()

syntax on
filetype plugin indent on

" 4 spaces instead of tabs
set tabstop=4
set shiftwidth=4
set expandtab
