inoremap jj <Esc>
set incsearch
set number

" Pathogen for plugins
" https://github.com/tpope/vim-pathogen
execute pathogen#infect()

syntax on
filetype plugin indent on

" 4 spaces instead of tabs
set tabstop=4
set shiftwidth=4
set expandtab

" 2 spaces for Rails
autocmd Filetype html setlocal ts=2 sw=2 expandtab
autocmd Filetype ruby setlocal ts=2 sw=2 expandtab
autocmd Filetype javascript setlocal ts=4 sw=4 sts=0 noexpandtab
